### ISSUE TITLE
Runtime Error invalid memory...

### ISSUE THREAD

**Issue by rhatdan** [cpuguy83/go-md2man#34]
```
 make  GOMD2MAN=~/bin/go-md2man 
/home/dwalsh/bin/go-md2man -in buildah.md -out buildah.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4daf1b]

goroutine 1 [running]:
github.com/cpuguy83/go-md2man/md2man.(*roffRenderer).handleTableCell(0xc4200784b0, 0x5b14e0, 0xc4200dbb20, 0xc4200f2dc0, 0x201)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/md2man/roff.go:269 +0x5b
github.com/cpuguy83/go-md2man/md2man.(*roffRenderer).RenderNode(0xc4200784b0, 0x5b14e0, 0xc4200dbb20, 0xc4200f2dc0, 0x1, 0x0)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/md2man/roff.go:156 +0x66c
github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday.Run.func1(0xc4200f2dc0, 0x4d9e01, 0x0)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/markdown.go:392 +0x5a
github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday.(*Node).Walk(0xc4200b0500, 0xc4200d7e18)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/node.go:284 +0x56
github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday.Run(0xc4200e6000, 0x1110, 0x1e00, 0xc4200d7e98, 0x2, 0x2, 0xc42000c050, 0x200, 0xc4200e6000)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/vendor/github.com/russross/blackfriday/markdown.go:391 +0x281
github.com/cpuguy83/go-md2man/md2man.Render(0xc4200e6000, 0x1110, 0x1e00, 0x1110, 0x1e00, 0x0)
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/md2man/md2man.go:11 +0xdc
main.main()
	/home/dwalsh/go/src/github.com/cpuguy83/go-md2man/md2man.go:35 +0x143
make: *** [Makefile:9: buildah.1] Error 2
```

**Comment by rhatdan** [comment]
Seems to not like tables with a struct like.

```
| Command               | Description                                                                                          |
| --------------               | ----------------------------------------------------------------------------------- |
```
Previous versions worked fine.

**Comment by rhatdan** [comment]
Here is the man page file causing the issue.
[buildah.txt](https://github.com/cpuguy83/go-md2man/files/1696822/buildah.txt)

**Comment by cpuguy83** [comment]
Is this with master?

**Comment by cpuguy83** [comment]
In the meantime I tagged v1.0.8 which has all the latest fixes.

**Comment by rhatdan** [comment]
Yes it is in master.  Thanks for taking a look.

**Comment by estesp** [comment]
PR #36 renders your table correctly now.

**Comment by cpuguy83** [comment]
Thanks @estesp!

@rhatdan Note that the roff output still isn't quite right due to the formatting at the end of the markdown table.

```markdown
| buildah-version(1)    | Display the Buildah Version Information
                                               |
```
